### ISSUE TITLE
[DEVELOP]Develop 1차 전체 merge 추가 기능 보고

### ISSUE THREAD

**Issue by eunseongjo** [Pixel-Power/Pixstar-guide#15]
**추가된 기능**

1. [MEMBER]로그인 기능 구현
  -  로그인(id,pw)생성
  -  생성 후 로그인 완료 표시
  -  완료 후 메인페이지 이동

2. [MAIN][반응형 Navbar 생성(토글 생성전)]
  - 반응형 Navbar 생성
 
3. [HEADER][헤더 생성, 페이지 연결]
  - 헤더 2가지와 페이지 연결(Link)

4. [FEATURE][MAIN][Body 박스 레이아웃 및 형상 구현]
  - 메인페이지의 박스 레이아웃 및 형상 초기구현

**Comment by nunu1101** [comment]
확인하였습니다.
