### ISSUE TITLE
[FEATURE][MAIN][Body 레이아웃 및 형상 구현 / Header, Navbar, Footer 레이아웃 구현]

### ISSUE THREAD

**Issue by eunseongjo** [Pixel-Power/Pixstar-guide#16]
## 어떤 기능인가요?
 > 메인페이지의 Body 레이아웃 및 형상 구현
> Header, Navbar, Footer 레이아웃 구현(현재 위치가 부정확함)

## 작업 상세 내용
- [ ] Body 레이아웃
- [ ] Body 형상 구현
- [ ] Header, Navbar, Footer 레이아웃 구현

**Comment by nunu1101** [comment]
확인하였습니다.
