### ISSUE TITLE
[FEATURE][MAIN][반응형 Navbar 생성(토글 생성전)]

### ISSUE THREAD

**Issue by nunu1101** [Pixel-Power/Pixstar-guide#4]
## 어떤 기능인가요?
> 반응형 Navbar 생성되었습니다.

## 작업 상세 내용
- [O] 반응형 Navbar 생성
- [ ] TODO
- [ ] TODO

## 참고할만한 자료(선택)
![image](https://github.com/Pixel-Power/Pixstar-guide/assets/134928447/c81cf856-a003-419f-9347-0e81d021105f)

## 참고 컴포넌트,페이지
- components -> Navbar.js , Navbar.module.css 참고해주세요

**Comment by rlawlsdyd5932** [comment]
확인
