### ISSUE TITLE
[FEATURE][RESTAURANT][예약상세내역페이지 링크 이동 및 지도 기능 추가]

### ISSUE THREAD

**Issue by KANGMINSEO0** [Pixel-Power/Pixstar-guide#43]
## 어떤 기능인가요?
> 예약하기를 누르면 예약 상세 내역 페이지로 이동, 식당위치로 이동하는 버튼 추가

## 작업 상세 내용
- [x] 예약하기 버튼에 링크를 이용하여 예약상세내역페이지로 이동
- [x] 지도에 마크 위치로 이동하는 버튼 추가
- [x] 버튼 클릭시 색상 변경 css 적용

**Comment by nunu1101** [comment]
머지하였습니다 이슈 닫겠습니다.
