### ISSUE TITLE
[FEATURE][MAIN][Body 박스 레이아웃 및 형상 구현]

### ISSUE THREAD

**Issue by eunseongjo** [Pixel-Power/Pixstar-guide#7]
## 어떤 기능인가요?
> 메인페이지의 박스 레이아웃 및 형상 초기구현

## 작업 상세 내용
- [ ] 메인페이지 박스 레이아웃 및 형상 초기 구현

## 참고할만한 자료(선택)
![image](https://github.com/Pixel-Power/Pixstar-guide/assets/152046800/7ac7088c-1eb3-4587-bedc-235cea8d4598)

## 참고할만한 컴포넌트(선택)
components -> Main.js , Main.module.css 참고해주세요

**Comment by rlawlsdyd5932** [comment]
확인
