### ISSUE TITLE
[FILE][RESTAURANT][레스토랑 조회 결과 및 상세 페이지 이름 변경]

### ISSUE THREAD

**Issue by nunu1101** [Pixel-Power/Pixstar-guide#8]
## 어떤 기능인가요?
> 현재 레스토랑 관련 파일명 오류로 인하여 파일명 변경해야 할 것 같습니다. 
> 하이픈(-) 제거 후 카멜케이스로 변경하는 것에 대해 댓글 달아주세요.

## 작업 상세 내용
- [x] Restaurant-detail -> RestaurantDetail
- [x] Restaurant-search-result -> RestaurantSearchResult

**Comment by rlawlsdyd5932** [comment]
확인

**Comment by Bini0104** [comment]
b

**Comment by KANGMINSEO0** [comment]
레스토랑 조회 결과 풀리퀘스트는 머지 했습니다.

**Comment by nunu1101** [comment]
파일명 그대로 -> 컴포넌트명은 카멜케이스로 작성
