### ISSUE TITLE
[FEATURE][CANCELMEMBER][회원 탈퇴 페이지]

### ISSUE THREAD

**Issue by Bini0104** [Pixel-Power/Pixstar-guide#82]
## 어떤 기능인가요?
> 마이페이지에서 넘어가는 회원탈퇴 페이지 생성

## 작업 상세 내용
- 회원탈퇴 버튼 클릭시 탈퇴 결정여부을 선택할 시 탈퇴/취소가 진행된다.

**Comment by nunu1101** [comment]
그냥 닫을게요 ㅎㅎ
