### ISSUE TITLE
[FEATURE][MYPAGE]예약상세페이지와 연결

### ISSUE THREAD

**Issue by KANGMINSEO0** [Pixel-Power/Pixstar-guide#97]
## 어떤 기능인가요?
> 마이페이지의 예약내역조회 페이지 -> 예약상세페이지 연결

## 작업 상세 내용
- [x] 마이페이지의 예약내역조회 페이지 -> 예약상세페이지 연결
- [x] userCode와 예약 정보 넘기기
- [x] TODO

**Comment by Bini0104** [comment]
해결 된 거다 이건 해결된 게 확실하다
